### ISSUE TITLE
Standalone dump of .bank files?

### ISSUE THREAD

**Issue by TheDavidJohnson** [bgbennyboy/Telltale-Music-Extractor#2] opened 2015-10-29 15:01 UTC
I see that you've added support for dumping the contents of .bank files. Is there a way to utilize just this function by itself? 

I've gotten far enough that I see the audio files I'm looking for are in a .bank file, but I'm not sure how to proceed.

Thanks!

**Comment by MrPowerGamerBR** [comment] 2015-10-29 16:10
:+1: 

I also need this feature (I sucessfully extracted the Minecraft Story Mode audio ".ttarch2" (this extractor failed when I tried), however, after extracting, the audios are in the ".bank" files, which failed when extracting with fsbext.

**Comment by bgbennyboy** [comment] 2015-10-29 16:34
I'm releasing a new version of the program in about 10 minutes that does the extracting automatically.
Dumping from the bank files is still a bit fiddly and I'd be grateful for any testing of the new version

**Comment by TheDavidJohnson** [comment] 2015-10-29 16:55
I'd be delighted to test. I'm actually doing the same thing that @MrPowerGamerBR mentioned.

Should we start from the .ttarch2 file(s) or the .bank file(s)?

**Comment by bgbennyboy** [comment] 2015-10-29 17:10
The ttarch2 files, the tool will find the appropriate bank files

**Comment by TheDavidJohnson** [comment] 2015-10-29 17:14
Excellent. Let me know when you post the update and I'll test today for you

**Comment by bgbennyboy** [comment] 2015-10-29 17:48
Done http://quickandeasysoftware.net/

**Comment by MrPowerGamerBR** [comment] 2015-10-29 17:56
@bgbennyboy I downloaded it and tried extracting the "MCSM_pc_Minecraft101_ms.ttarch2", however, when extracting, a error popped up:

"Error while parsing the Ttarch bundle C:\Program Files\Minecraft Story Mode...MCSM_pc_Minecraft101_ms.ttarch2"

This happened when trying to use the "Select File..." option, the "Select Folder..." shows that "No audio data file could be found"

**Comment by bgbennyboy** [comment] 2015-10-29 18:01
Strange, I've just done the same.
Open file > MCSM_pc_Minecraft101_ms.ttarch2
And its working fine

**Comment by bgbennyboy** [comment] 2015-10-29 18:06
That error message means it cant even open the .ttarch2 bundle to parse the files inside. I cant see any reason why you'd get that unless your bundle was somehow different to mine

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:08
@bgbennyboy strange '-' However, when extracting "ttarchext" it extracts the file correctly (however, all audios are inside the .bank file)

Also, you are trying with what Minecraft Story Mode version? Steam or GOG? (I think the files are the same, however, it doesn't cost anything to ask)

**Comment by TheDavidJohnson** [comment] 2015-10-29 18:10
I downloaded the latest version and am currently extracting the same file that @MrPowerGamerBR mentioned above. I haven't gotten any errors, but the FSB Bank Dumper is still running so I haven't played the files back yet.

Incidentally,the error @MrPowerGamerBR mentioned was the same one I got when I used the previous version (1.5.1.3) of the Music Extractor tool.

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:11
@TheDavidJohnson strange, because I'm 100% sure that I downloaded the program again from @bgbennyboy website, I will try again later.

**Comment by TheDavidJohnson** [comment] 2015-10-29 18:11
FWIW, I'm using the Steam version

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:13
Oh, I found the problem.

When I go here: http://quickandeasysoftware.net/software/telltale-music-extractor , the links points to the 1.5.1.3 version, so, with my "amazing" changing text skills, I changed the "1.5.1.3" to "1.5.1.4" in the URL, and the correct version was downloaded.

Here is a direct link to the 1.5.1.4 version: http://quickandeasysoftware.net/files/TelltaleMusicExtractor1.5.1.4.zip

I will test with the GOG version.

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:15
...and, yes, that was the problem, for me, the website was downloading the 1.5.1.3 version instead of the latest version.

Now it is extracting the archive files in the GOG version... :smile:

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:18
While extracting, I opened some extracted files to test, and it seems that the audio files are extracting correctly!

**Comment by bgbennyboy** [comment] 2015-10-29 18:19
How strange, the site is using caching, but when I view the site through the cache I get the updated page. Oh well.

**Comment by TheDavidJohnson** [comment] 2015-10-29 18:22
Just got an error:
![image](https://cloud.githubusercontent.com/assets/1313680/10827990/5aed0654-7e48-11e5-83dc-677e47058f77.png)
This occurred after quite some time of running. I wasn't actually looking when the error happened, so I don't have much more info for you.

The target folder has 689 files in it....

Oh wait. I see it. The drive ran out of space.

**Comment by TheDavidJohnson** [comment] 2015-10-29 18:23
10.2 GB in that folder... WOW! I need to make more room... I guess I have to start over?

**Comment by bgbennyboy** [comment] 2015-10-29 18:25
It does take an awful lot of space as it extracts raw wav files. Episode 2 took around 5GB, I cant remember what size EP1 was when extracted.
Yes, you'll need to free up space and try again.

**Comment by TheDavidJohnson** [comment] 2015-10-29 18:27
OK. Thanks.

Also... it seems that the files have silence at the beginning, and cut off abruptly at the end. (At first I thought they were empty, but I left one playing and got a surprise.

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:33
@TheDavidJohnson I had a audio with almost the same issue (almost)

The "ChickensRelease.wav" is a audio with 3:30 seconds of duration, with the audio almost empty, except for the final, which is... well, chickens making sound.

I don't know if this is a issue from the extractor (because of the 99% empty sound) or if Telltale made this audio with 99% empty audio.

**Comment by TheDavidJohnson** [comment] 2015-10-29 18:39
Right. I noticed varying lengths of silence at the beginning of all the files I tested. Since I'm not interested in the SFX and files of that sort anyway, no big deal.

A couple of weird examples from the music files, though: 

* mus_theme01.wav has 6 seconds of silence at the beginning, and ends abruptly (as though there were a mismatch in some underlying source)
* mus_temp_Credits.wav (6 seconds of silence up front, abrupt ending)
* mus_temp_paleBlueDotMulti01.wav (and other files containing the string 'multi') seem to be silent throughout

Hope this helps, @bgbennyboy !

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:44
@bgbennyboy "mus_temp_noMoreCreepers01.wav" also have a silence before starting, it also has as a abrupt ending.

However, it seems that this track loops in-game, so, if you copy and paste the music (cutting the silence from the beginning, of course) and place in the end of the music, it will be repeated seamlessy, so, this is maybe the cause of why some musics has abrupt ending, because it should loop.

**Comment by bgbennyboy** [comment] 2015-10-29 18:45
Its to do with the way the audio is extracted. The music is 'played' through FMOD and outputted to a wav file, its all very wonky and the silences at the beginning of tracks are an unfortunate side effect. In my testing I only found it cutting off on looping tracks.

I tested mostly with Game of Thrones, I'm running it with Minecraft 101 again now though and finding some 'silent' sounds which indicates that it might be missing some required .bank files when dumping.

**Comment by TheDavidJohnson** [comment] 2015-10-29 18:48
Looping had occurred to me, and that definitely makes sense for some of these tracks. Also, certainly time spent listening to some of these in-game is quite short, and with the nature of the way these games are built, they probably don't need to create endings for some of the ones that don't loop.

Thanks for your hard work on this, @bgbennyboy -- I'm glad to provide any other troubleshooting/testing I can. 

Also, nice testing with you, @MrPowerGamerBR !

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:51
The only issue is with the Multi tracks, however, if it isn't on the main bank, where it should be? Also, there is 3 .banks on the "MCSM_pc_Minecraft101_ms.ttarch2" archive, however I have 99% that @bgbennyboy made that those 3 banks are extracted.

There is only 3 other files in the Archive folders that has "ms" on the name, the  "MCSM_pc_Boot_ms.ttarch2", "MCSM_pc_Menu_ms.ttarch2", "MCSM_pc_Project_ms.ttarch2" (organized from smaller file > bigger file), maybe the rest is in the Project_ms?

**Comment by MrPowerGamerBR** [comment] 2015-10-29 18:54
Well, I was wrong, from all of those 3 files, only "MCSM_pc_Boot_ms.ttarch2" can be extracted, and it does have some audio files, but nothing related to the "Multi" track.

**Comment by bgbennyboy** [comment] 2015-10-29 18:56
Thank you both for testing this. The program automatically finds the appropriate banks in the other .ttarch2 files and extracts them, its possible that I have missed one, I'll look into it later.
As I say, I mainly tested this with Game of Thrones, so its quite possible that there are some things that need changing for Minecraft to all dump correctly.

**Comment by bgbennyboy** [comment] 2015-10-29 19:08
Actually I think I've just found a better way of extracting the audio that's a lot quicker and cleaner than the current method ¬¬ 
There's probably a newer version coming later this week :~

**Comment by TheDavidJohnson** [comment] 2015-10-29 19:41
Sounds good to me! 👊

**Comment by MrPowerGamerBR** [comment] 2015-10-30 15:45
After fiddling around (I was uploading the OST to YouTube), I found something interesting...

If you extract the Episode 1 files, there is a empty audio called "mus_autoChickenFarm.wav", which is a empty file, however, if you extract the Episode 2 files, there is the "mus_autoChickenFarm.wav" and there is also ANOTHER file called "mus_autoChickenFarm5section.wav", which contains audio.

Maybe the empty audios are only for temporary audios that will be used on other episodes? Also, Episode 2 also contains repeated audios from Episode 1.

**Comment by bgbennyboy** [comment] 2015-10-31 00:22
It might be worth holding off uploading for now.
I've made a new way of dumping from the bank files, its a lot quicker, takes less space and is more accurate. Things like the sounds with nothing in them or long gaps should be fixed with this method. From a quick comparison it seems like the quality is better too. In short - much better all round.

**Comment by MrPowerGamerBR** [comment] 2015-10-31 00:32
@bgbennyboy well, now I already uploaded all the functional tracks from Episode 1 and 2 :stuck_out_tongue: 

Well, that will still be useful to get another tracks from the game, a lot of tracks (maybe 40%?) is only empty audio, maybe your new version will get everything correctly :+1: 

(I was going to donate to you, but it seems that PayPal simply can't send anything "Sorry, we can't process your payment now", well, why can't PayPal process a simple 5$ donation? :disappointed: )

**Comment by bgbennyboy** [comment] 2015-10-31 12:20
I've now released a new version of the program that fixes these problems so I'm going to close this. Thank you both for all your help.

**Comment by MrPowerGamerBR** [comment] 2015-11-04 21:21
...and finally donated!

Also, I tested v1.5.4.5, it extracts WAY quicker and all tracks are extracted properly! Thanks @bgbennyboy :+1:

**Comment by TheDavidJohnson** [comment] 2015-11-11 01:30
OK I finally got a chance to test the new version. If I choose Minecraft Story Mode Episode 1, I get these errors:

![image](https://cloud.githubusercontent.com/assets/1313680/11081342/bf83727e-87e9-11e5-904d-15665ec16439.png)

then

![image](https://cloud.githubusercontent.com/assets/1313680/11081347/c97d5222-87e9-11e5-9e5c-2298adf438e8.png)

However... if I select Minecraft Story Mode Episode 2 (Assembly Required), what happens is a thing of beauty. It extracts much more quickly, the audio files are neatly trimmed, and everything is amazing!

Let me know if I can help troubleshoot whatever is going on with Episode 1.

Thank you!

**Comment by TheDavidJohnson** [comment] 2015-11-11 01:35
Quick follow-up. Rather than selecting "Minecraft Story Mode" from the menu, I just decided to try opening the file:

`MCSM_pc_Minecraft101_ms.ttarch2`

...and things are happening. Looks like it's working. I'll edit this when it finishes to update as to how it worked out.

Thanks!

**Comment by bgbennyboy** [comment] 2015-11-11 18:59
Thats a weird one, thanks for letting me know, I'll look into it now

**Comment by bgbennyboy** [comment] 2015-11-11 19:43
When its dumping episode 1 it also dumps the other music and sounds that are common to all episodes. It only does it with episode 1 because it'd be pointless to duplicate it for each episode.

For minecraft 101 it looks for MCSM_pc_Project_ms.ttarch2 and dumps common.bank from it. That error in your screenshot should only occur if it cant dump the extra bank files so it should only show up if "MCSM_pc_Project_ms.ttarch2" isn't in the same folder.

I cant work out why choosing the episode from the menu should make the error appear but directly choosing the episode 1 music ttarch wouldnt. They both lead to the same dumping code. Hmm...

**Comment by TheDavidJohnson** [comment] 2015-11-11 19:56
It definitely seems odd to me, too, but of course I don't have nearly the familiarity with all of this that you do.

I pointed the software to a separate 'target' folder when I extracted from Episode 1 (since I got Episode 2 to extract successfully first). After the dump finished (again, from pointing directly to the .ttarch2 file), my target folder has 2,652 files in it which are, presumably, the Episode 1 files and the common files you referred to.

Just to satisfy my curiosity curiosity, I double checked and `MCSM_pc_Project_ms.ttarch2` is in the same folder as `MCSM_pc_Minecraft101_ms.ttarch2`

I don't know if this matters or helps, but I keep my Steam library on Drive D:/ -- it doesn't appear that you're hardcoding any drive letters anywhere, but I thought I'd mention it in case that's the only difference between my setup and a 'typical' one.

Let me know if there's any other info I can provide you... and thanks for a great tool!

**Comment by bgbennyboy** [comment] 2015-11-12 22:36
Thanks for the helpful bug report, I've fixed the error. Doing a new release now

**Closed by bgbennyboy** 2015-11-12 22:36 UTC

**Comment by TheDavidJohnson** [comment] 2015-11-12 22:38
You're more than welcome. Glad it was useful. Thanks for the great software!

**Comment by TheDavidJohnson** [comment] 2016-01-14 21:37
I don't think I donated previously, so I just sent a few quid your way. Thanks again!
